# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b0efadd79ba193fabb268d3b82831741e17374bd666070544c6e47fe405610881c6c48ff1362bdfbc48860724f374b4d83cfb4ebe1f038601113171535c5be3

test:
  secret_key_base: 5d24beb8acea7331bb69fd2c6e960d56489f4f8c167a00ec7b52c691c07043104788f2edb4eb43fafd0c65a417a93ffa189eebe8bd751dab416c0f4500485141

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
